Repository checkmarx-ltd/Sonar-Plugin, pull requests merged in 2022-07, with the labels that each got.

#19 feature: adding Kotlin languaje
  src/main/java/com/checkmarx/sonar/CheckmarxPlugin.java
  src/main/java/com/checkmarx/sonar/cxpropfiles/CxKotlinProfile.java
  src/main/java/com/checkmarx/sonar/cxrules/CXProgrammingLanguage.java
  src/main/resources/com/checkmarx/sonar/profiles/kotlin-profile.xml
  src/main/resources/com/checkmarx/sonar/rules/kotlin-rules.xml
Labels: size/XXL

#18 Plug 18 missing rules
  pom.xml
  src/main/resources/com/checkmarx/sonar/profiles/apex-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/cpp-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/csharp-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/go-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/groovy-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/java-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/javascript-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/perl-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/php-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/plsql-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/python-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/vb6-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/vbnet-profile.xml
  src/main/resources/com/checkmarx/sonar/rules/apex-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/cpp-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/csharp-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/go-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/groovy-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/java-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/javascript-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/objc-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/perl-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/php-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/plsql-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/python-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/vb6-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/vbnet-rules.xml
Labels: size/XXL

#21 fix: SCA vulnerabilities
  pom.xml
Labels: size/M

#20 Sonar enhancements
  src/main/resources/static/CxIcon24x24.png
  src/main/resources/static/CxIcon48x48.png
Labels: size/XS

#22 Sonar rules integration branch
  pom.xml
  src/main/java/com/checkmarx/sonar/CheckmarxPlugin.java
  src/main/java/com/checkmarx/sonar/cxpropfiles/CxKotlinProfile.java
  src/main/java/com/checkmarx/sonar/cxrules/CXProgrammingLanguage.java
  src/main/resources/com/checkmarx/sonar/profiles/apex-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/cpp-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/csharp-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/go-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/groovy-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/java-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/javascript-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/kotlin-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/perl-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/php-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/plsql-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/python-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/vb6-profile.xml
  src/main/resources/com/checkmarx/sonar/profiles/vbnet-profile.xml
  src/main/resources/com/checkmarx/sonar/rules/apex-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/cpp-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/csharp-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/go-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/groovy-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/java-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/javascript-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/kotlin-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/objc-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/perl-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/php-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/plsql-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/python-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/vb6-rules.xml
  src/main/resources/com/checkmarx/sonar/rules/vbnet-rules.xml
  src/main/resources/static/CxIcon24x24.png
  src/main/resources/static/CxIcon48x48.png
Labels: size/XXL
